name: circle
description: "A Sickle Cell App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 0.1.4+11
# Things to note when versioning. Do not touch the build number, i.e (X.Y.Z+N) where N is the build number.
# It will be automatically incremented by the CI/CD pipeline.
# Also, also, when merging `release` branches, do not `rebase` use only `merge` for pull requests,
# so the release would split the commits for this release properly

environment:
  sdk: ^3.7.0-183.0.dev


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.270
  percent_indicator: ^4.2.3
  fl_chart: ^0.70.1
  fpdart: ^1.1.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_crashlytics: ^4.3.3
  firebase_analytics: ^11.4.3
  google_sign_in: ^6.2.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.0.15
  mesh_gradient: ^1.3.8
  flutter_spinkit: ^5.2.1
  intl: ^0.20.1
  objectbox: ^4.2.0
  objectbox_flutter_libs: ^4.2.0
  path: ^1.9.0
  cached_network_image: ^3.4.1
  jiffy: ^6.3.2
  hugeicons: ^0.0.7
  springster: ^0.4.0
  auto_route: ^9.3.0+1
  uuid: ^4.5.1
  generic_selector: ^0.1.0
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  icon_font_generator: ^4.0.0
  mocktail: ^1.0.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3
  objectbox_generator: ^4.2.0
  flutter_gen_runner: ^5.8.0
  auto_route_generator: ^9.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/svg/illustrations/emojis/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
