// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth/models/user/app_user.dart';
import 'features/auth/models/user/user_preferences.dart';
import 'features/auth/models/user/user_profile.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 9210468346883610997),
      name: 'AppUser',
      lastPropertyId: const obx_int.IdUid(10, 7776106648647357425),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6793769419637763149),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 417247235985229651),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5185424966544459360),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 927931047185036496),
            name: 'photoUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8273309073968860340),
            name: 'isAnonymous',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2555433748586013967),
            name: 'isEmailVerified',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7223991870356115469),
            name: 'isPhoneVerified',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8399786612049634084),
            name: 'profileId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 4140018892505963279),
            relationTarget: 'UserProfile'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 7776106648647357425),
            name: 'preferencesId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 7305761162520707228),
            relationTarget: 'UserPreferences')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7166028067144916976),
      name: 'UserProfile',
      lastPropertyId: const obx_int.IdUid(18, 1583331589492315386),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7096745133435402091),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5360133605550174324),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2642145193887279486),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4395116447830403324),
            name: 'displayName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8429495187897421578),
            name: 'age',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 269684340983521806),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 705516932664929996),
            name: 'photoUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 1664576630604936704),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7192482139177737210),
            name: 'painSeverity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1724840226639888386),
            name: 'crisisFrequency',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6629241393886714269),
            name: 'height',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7408718016768229555),
            name: 'weight',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 8969005121810407638),
            name: 'bmi',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 7467163394291670971),
            name: 'bloodGroup',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 1424233479968241717),
            name: 'allergies',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 5346806588601411509),
            name: 'medicalConditions',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 3418391106783914792),
            name: 'dbGender',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 1583331589492315386),
            name: 'dbGenotype',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 867207695587786430),
      name: 'UserPreferences',
      lastPropertyId: const obx_int.IdUid(9, 8332419882270310101),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6382851924054177629),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1938034445264548325),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6756802899985026265),
            name: 'isFirstTime',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4137700724415044066),
            name: 'isOnboarded',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7538616858440401534),
            name: 'lastUpdated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4322896623179610370),
            name: 'dbThemeMode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 589524113363230822),
            name: 'dbVolumeUnit',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5351588759555286712),
            name: 'dbLengthUnit',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8332419882270310101),
            name: 'dbMassUnit',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 867207695587786430),
      lastIndexId: const obx_int.IdUid(3, 7305761162520707228),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [8176574082609213585],
      retiredPropertyUids: const [1282289976025498362],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    AppUser: obx_int.EntityDefinition<AppUser>(
        model: _entities[0],
        toOneRelations: (AppUser object) =>
            [object.profile, object.preferences],
        toManyRelations: (AppUser object) => {},
        getId: (AppUser object) => object.id,
        setId: (AppUser object, int id) {
          object.id = id;
        },
        objectToFB: (AppUser object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final emailOffset = fbb.writeString(object.email);
          final photoUrlOffset = object.photoUrl == null
              ? null
              : fbb.writeString(object.photoUrl!);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, emailOffset);
          fbb.addOffset(3, photoUrlOffset);
          fbb.addBool(4, object.isAnonymous);
          fbb.addBool(5, object.isEmailVerified);
          fbb.addBool(6, object.isPhoneVerified);
          fbb.addInt64(7, object.profile.targetId);
          fbb.addInt64(9, object.preferences.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final isAnonymousParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final isEmailVerifiedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final isPhoneVerifiedParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 16);
          final photoUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final object = AppUser(
              id: idParam,
              email: emailParam,
              isAnonymous: isAnonymousParam,
              uid: uidParam,
              isEmailVerified: isEmailVerifiedParam,
              isPhoneVerified: isPhoneVerifiedParam,
              photoUrl: photoUrlParam);
          object.profile.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.profile.attach(store);
          object.preferences.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          object.preferences.attach(store);
          return object;
        }),
    UserProfile: obx_int.EntityDefinition<UserProfile>(
        model: _entities[1],
        toOneRelations: (UserProfile object) => [],
        toManyRelations: (UserProfile object) => {},
        getId: (UserProfile object) => object.id,
        setId: (UserProfile object, int id) {
          object.id = id;
        },
        objectToFB: (UserProfile object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final displayNameOffset = object.displayName == null
              ? null
              : fbb.writeString(object.displayName!);
          final emailOffset =
              object.email == null ? null : fbb.writeString(object.email!);
          final photoUrlOffset = object.photoUrl == null
              ? null
              : fbb.writeString(object.photoUrl!);
          final phoneOffset =
              object.phone == null ? null : fbb.writeString(object.phone!);
          final crisisFrequencyOffset = object.crisisFrequency == null
              ? null
              : fbb.writeString(object.crisisFrequency!);
          final bloodGroupOffset = object.bloodGroup == null
              ? null
              : fbb.writeString(object.bloodGroup!);
          final allergiesOffset = object.allergies == null
              ? null
              : fbb.writeList(object.allergies!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final medicalConditionsOffset = object.medicalConditions == null
              ? null
              : fbb.writeList(object.medicalConditions!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final dbGenderOffset = object.dbGender == null
              ? null
              : fbb.writeString(object.dbGender!);
          final dbGenotypeOffset = object.dbGenotype == null
              ? null
              : fbb.writeString(object.dbGenotype!);
          fbb.startTable(19);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, displayNameOffset);
          fbb.addInt64(4, object.age);
          fbb.addOffset(5, emailOffset);
          fbb.addOffset(6, photoUrlOffset);
          fbb.addOffset(7, phoneOffset);
          fbb.addInt64(8, object.painSeverity);
          fbb.addOffset(9, crisisFrequencyOffset);
          fbb.addFloat64(10, object.height);
          fbb.addFloat64(11, object.weight);
          fbb.addFloat64(12, object.bmi);
          fbb.addOffset(13, bloodGroupOffset);
          fbb.addOffset(14, allergiesOffset);
          fbb.addOffset(15, medicalConditionsOffset);
          fbb.addOffset(16, dbGenderOffset);
          fbb.addOffset(17, dbGenotypeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final ageParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final displayNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final photoUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 16);
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 18);
          final crisisFrequencyParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final painSeverityParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
          final heightParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 24);
          final weightParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 26);
          final bmiParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 28);
          final bloodGroupParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final allergiesParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 32);
          final medicalConditionsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 34);
          final object = UserProfile(
              id: idParam,
              uid: uidParam,
              name: nameParam,
              age: ageParam,
              displayName: displayNameParam,
              email: emailParam,
              photoUrl: photoUrlParam,
              phone: phoneParam,
              crisisFrequency: crisisFrequencyParam,
              painSeverity: painSeverityParam,
              height: heightParam,
              weight: weightParam,
              bmi: bmiParam,
              bloodGroup: bloodGroupParam,
              allergies: allergiesParam,
              medicalConditions: medicalConditionsParam)
            ..dbGender = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 36)
            ..dbGenotype = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 38);

          return object;
        }),
    UserPreferences: obx_int.EntityDefinition<UserPreferences>(
        model: _entities[2],
        toOneRelations: (UserPreferences object) => [],
        toManyRelations: (UserPreferences object) => {},
        getId: (UserPreferences object) => object.id,
        setId: (UserPreferences object, int id) {
          object.id = id;
        },
        objectToFB: (UserPreferences object, fb.Builder fbb) {
          final uidOffset =
              object.uid == null ? null : fbb.writeString(object.uid!);
          final dbThemeModeOffset = object.dbThemeMode == null
              ? null
              : fbb.writeString(object.dbThemeMode!);
          final dbVolumeUnitOffset = object.dbVolumeUnit == null
              ? null
              : fbb.writeString(object.dbVolumeUnit!);
          final dbLengthUnitOffset = object.dbLengthUnit == null
              ? null
              : fbb.writeString(object.dbLengthUnit!);
          final dbMassUnitOffset = object.dbMassUnit == null
              ? null
              : fbb.writeString(object.dbMassUnit!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addBool(2, object.isFirstTime);
          fbb.addBool(3, object.isOnboarded);
          fbb.addInt64(4, object.lastUpdated?.millisecondsSinceEpoch);
          fbb.addOffset(5, dbThemeModeOffset);
          fbb.addOffset(6, dbVolumeUnitOffset);
          fbb.addOffset(7, dbLengthUnitOffset);
          fbb.addOffset(8, dbMassUnitOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastUpdatedValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final isFirstTimeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final isOnboardedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final lastUpdatedParam = lastUpdatedValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(lastUpdatedValue);
          final object = UserPreferences(
              id: idParam,
              uid: uidParam,
              isFirstTime: isFirstTimeParam,
              isOnboarded: isOnboardedParam,
              lastUpdated: lastUpdatedParam)
            ..dbThemeMode = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..dbVolumeUnit = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..dbLengthUnit = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..dbMassUnit = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 20);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppUser] entity fields to define ObjectBox queries.
class AppUser_ {
  /// See [AppUser.id].
  static final id =
      obx.QueryIntegerProperty<AppUser>(_entities[0].properties[0]);

  /// See [AppUser.uid].
  static final uid =
      obx.QueryStringProperty<AppUser>(_entities[0].properties[1]);

  /// See [AppUser.email].
  static final email =
      obx.QueryStringProperty<AppUser>(_entities[0].properties[2]);

  /// See [AppUser.photoUrl].
  static final photoUrl =
      obx.QueryStringProperty<AppUser>(_entities[0].properties[3]);

  /// See [AppUser.isAnonymous].
  static final isAnonymous =
      obx.QueryBooleanProperty<AppUser>(_entities[0].properties[4]);

  /// See [AppUser.isEmailVerified].
  static final isEmailVerified =
      obx.QueryBooleanProperty<AppUser>(_entities[0].properties[5]);

  /// See [AppUser.isPhoneVerified].
  static final isPhoneVerified =
      obx.QueryBooleanProperty<AppUser>(_entities[0].properties[6]);

  /// See [AppUser.profile].
  static final profile =
      obx.QueryRelationToOne<AppUser, UserProfile>(_entities[0].properties[7]);

  /// See [AppUser.preferences].
  static final preferences = obx.QueryRelationToOne<AppUser, UserPreferences>(
      _entities[0].properties[8]);
}

/// [UserProfile] entity fields to define ObjectBox queries.
class UserProfile_ {
  /// See [UserProfile.id].
  static final id =
      obx.QueryIntegerProperty<UserProfile>(_entities[1].properties[0]);

  /// See [UserProfile.uid].
  static final uid =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[1]);

  /// See [UserProfile.name].
  static final name =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[2]);

  /// See [UserProfile.displayName].
  static final displayName =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[3]);

  /// See [UserProfile.age].
  static final age =
      obx.QueryIntegerProperty<UserProfile>(_entities[1].properties[4]);

  /// See [UserProfile.email].
  static final email =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[5]);

  /// See [UserProfile.photoUrl].
  static final photoUrl =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[6]);

  /// See [UserProfile.phone].
  static final phone =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[7]);

  /// See [UserProfile.painSeverity].
  static final painSeverity =
      obx.QueryIntegerProperty<UserProfile>(_entities[1].properties[8]);

  /// See [UserProfile.crisisFrequency].
  static final crisisFrequency =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[9]);

  /// See [UserProfile.height].
  static final height =
      obx.QueryDoubleProperty<UserProfile>(_entities[1].properties[10]);

  /// See [UserProfile.weight].
  static final weight =
      obx.QueryDoubleProperty<UserProfile>(_entities[1].properties[11]);

  /// See [UserProfile.bmi].
  static final bmi =
      obx.QueryDoubleProperty<UserProfile>(_entities[1].properties[12]);

  /// See [UserProfile.bloodGroup].
  static final bloodGroup =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[13]);

  /// See [UserProfile.allergies].
  static final allergies =
      obx.QueryStringVectorProperty<UserProfile>(_entities[1].properties[14]);

  /// See [UserProfile.medicalConditions].
  static final medicalConditions =
      obx.QueryStringVectorProperty<UserProfile>(_entities[1].properties[15]);

  /// See [UserProfile.dbGender].
  static final dbGender =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[16]);

  /// See [UserProfile.dbGenotype].
  static final dbGenotype =
      obx.QueryStringProperty<UserProfile>(_entities[1].properties[17]);
}

/// [UserPreferences] entity fields to define ObjectBox queries.
class UserPreferences_ {
  /// See [UserPreferences.id].
  static final id =
      obx.QueryIntegerProperty<UserPreferences>(_entities[2].properties[0]);

  /// See [UserPreferences.uid].
  static final uid =
      obx.QueryStringProperty<UserPreferences>(_entities[2].properties[1]);

  /// See [UserPreferences.isFirstTime].
  static final isFirstTime =
      obx.QueryBooleanProperty<UserPreferences>(_entities[2].properties[2]);

  /// See [UserPreferences.isOnboarded].
  static final isOnboarded =
      obx.QueryBooleanProperty<UserPreferences>(_entities[2].properties[3]);

  /// See [UserPreferences.lastUpdated].
  static final lastUpdated =
      obx.QueryDateProperty<UserPreferences>(_entities[2].properties[4]);

  /// See [UserPreferences.dbThemeMode].
  static final dbThemeMode =
      obx.QueryStringProperty<UserPreferences>(_entities[2].properties[5]);

  /// See [UserPreferences.dbVolumeUnit].
  static final dbVolumeUnit =
      obx.QueryStringProperty<UserPreferences>(_entities[2].properties[6]);

  /// See [UserPreferences.dbLengthUnit].
  static final dbLengthUnit =
      obx.QueryStringProperty<UserPreferences>(_entities[2].properties[7]);

  /// See [UserPreferences.dbMassUnit].
  static final dbMassUnit =
      obx.QueryStringProperty<UserPreferences>(_entities[2].properties[8]);
}
